### ISSUE TITLE
Persistent Bean Initialization Issues in sbp with Spring Boot 3.x

### ISSUE THREAD

**Issue by batugane** [hank-cp/sbp#47]
I'm encountering multiple bean initialization issues in a Spring Boot 3.x project using sbp version 3.1.22. The primary challenge involves an `UnsatisfiedDependencyException`, starting with the `SpringBootPluginManager` bean and persisting with others.

**Steps to Reproduce:**
1. Set up a Spring Boot project with a multi-subproject structure for plugin-oriented programming.
2. Incorporate `sbp-spring-boot-starter` in the dependencies.
3. Configure `application.properties` as per sbp guidelines.
4. Create a plugin project within the `plugins` directory.
5. Attempt to run the application.

I've basically followed the guide on readme. 

**Errors Encountered:**
The application fails to start, initially due to an `UnsatisfiedDependencyException` for `SpringBootPluginManager`. The error message indicates a missing bean:
```
2024-04-02T09:34:56.200+03:00 ERROR 40304 --- [pluginDemo] [           main] o.laxture.sbp.SpringBootPluginManager    : Error creating bean with name 'pluginManagerController': Unsatisfied dependency expressed through field 'pluginManager': No qualifying bean of type 'org.laxture.sbp.SpringBootPluginManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pluginManagerController': Unsatisfied dependency expressed through field 'pluginManager': No qualifying bean of type 'org.laxture.sbp.SpringBootPluginManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
...
```
Resolving this leads to similar issues with other beans.

**Attempted Solutions:**
- Utilizing a custom class loader.
- Adjusting `spring.factories`.
- Creating a custom `PluginManager` bean.
- Applying `scanBasePackages`.
- Downgrading Spring Boot and sbp

None of these attempts have successfully resolved the bean initialization issues.

**Additional Context:**
The problem seems to extend beyond a specific bean, suggesting a more systemic issue with the sbp setup or compatibility. 
I have set up a [GitHub repository](https://github.com/batugane/pluginDemo) for detailed inspection of the project.

**Request for Assistance:**
Guidance or suggestions to resolve these bean initialization challenges would be greatly appreciated.

---

**Comment by hank-cp** [comment]
Hi @batugane,

First of all, thanks for the nice written, the issue is described very clear and helpful. I checkout out repo and make a fixing patch [fix_configuration.patch](https://github.com/hank-cp/sbp/files/14902741/fix_configuration.patch) for it. You could apply the patch to your repo and it should be able to start successfully.

There two failed reasons:
1. You should name the package of plugin and app differently, otherwise the plugin spring context will scan into app's classpath, and construct duplicated beans which already created in app's application context.
2. There is a bug of excluding app's AutoConfigurations, it will occur when your plugin misses `application.properties` or `application.yml`, etc. So you can see I placed a empty `application.properties` file to walk around the bug. I will fix it on next release.

Just let you know that I also removed `META-INF` content in the patch, they are totally unnecessary and causing mis-configuration problems.

**Comment by hank-cp** [comment]
NP. pf4j-spring is for pure spring (not spring boot), so you will have to config all midwere from sketch. It would be easier for simple Spring projects, for example, you just need simple bean injection/singleton management.
